version: '3.4'

networks: 
  docker-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks: 
      - docker-network

  api:
    image: tomaszek92/lateness-manager-api
    ports:
      - "5001:80"
      - "5000:80"
    networks: 
      - docker-network
    depends_on:
      - 'postgres'

  web-client:
    image: tomaszek92/lateness-manager-web-client 
    environment:
      NODE_ENV: production
    ports:
      - "3000:80"
    networks: 
      - docker-network